# Generated by Django 5.1.2 on 2024-12-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='update',
            new_name='updated',
        ),
    ]
