# Generated by Django 5.1.2 on 2025-01-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pushToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
