# Generated by Django 5.1.2 on 2025-02-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_usuario_pushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
