# Generated by Django 5.1.2 on 2025-02-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_usuario_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_seen',
        ),
    ]
