# Generated by Django 5.1.2 on 2025-03-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_audio_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
